# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Pavel Linkesch
tagline:          'Web Developer'
description:      'A full stack web developer, a freelancer, and an open souce fan'
url:              http://linkesch.com
baseurl:          /

author:
  name:           'Pavel Linkesch'
  url:            https://twitter.com/linkesch

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
