# Dependencies
markdown:         kramdown
highlighter:      rouge

# Plugins
gems:
    - jekyll-paginate

# Permalinks
permalink:        pretty

# Setup
title:            Pavel Linkesch
tagline:          'Frontend Developer'
description:      'A lead frontend engineer and an <a href="https://github.com/orthes">open source</a> fan'
url:              http://linkesch.com/
baseurl:          /

author:
  name:           'Pavel Linkesch'
  url:            https://twitter.com/linkesch

paginate:         5
